version: '3.4'

services:
  mongo_db:
    image: mongo
    volumes:
      - mongodb:/var/lib/mongo

  users-service:
    build:
      context: .
      dockerfile: ./users_microservice/Dockerfile
    ports:
    #  - "2225"
      - "2225:2225"
    restart: always
    env_file:
      - user.env
      - commons.env

volumes:
  mongodb:
