apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  BROKER_ID_COMMAND: "hostname | cut -d'-' -f2"
  KAFKA_ADVERTISED_PORT: "9092"
  KAFKA_LISTENERS: "PLAINTEXT://:9092"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  KAFKA_CREATE_TOPICS: "logging:20:1"
  #KAFKA_BROKER_ID: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zoo-config
data:
  ZOO_MY_ID: "1"
