apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo-db"
  selector:
    matchLabels:
      db: mongo
  template:
    metadata:
      name: mongo-pod
      labels:
        db: mongo
    spec:
      containers:
        - image: mongo
          imagePullPolicy: ""
          name: mongo-db
          command: ["/bin/bash","-c",'source docker-entrypoint.sh mongod && mongod "--replSet" rs0 "--smallfiles" "--noprealloc"']
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-auth-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-auth-secret
                  key: password
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /var/lib/mongo
              name: mongodb

          startupProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            failureThreshold: 10
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            failureThreshold: 10
            periodSeconds: 30
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb-volume

